language: php
sudo: required
dist: trusty
group: edge

matrix:
  include:
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - SEND_COVERAGE=true
    - php: 7
    - php: 7.1
    - php: hhvm-3.9
    - php: hhvm-3.12
    - php: hhvm-nightly

                    
before_script:
  - mkdir build
  - mkdir -p build/logs
  - mkdir -p test/logs
  - travis_retry composer self-update
  - travis_retry composer --prefer-source --dev install
    
script: 
  - phpunit -v 

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.xml; fi
  #- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then coveralls ; fi